# values.yaml para instalar el operador ECK de Elastic
installCRDs: true

webhook:
  enabled: true

metrics:
  enabled: true

replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
