clusterName: elastic-dev
 
replicas: 1
 
esJavaOpts: "-Xmx1g -Xms1g"
 
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
 
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: managed-standard
  resources:
    requests:
      storage: 10Gi
 
nodeGroup: "default"
 
roles:
  master: "true"
  data: "true"
  ingest: "true"
 
persistence:
  enabled: true
 
security:
  enabled: false
 
service:
  type: ClusterIP
 
antiAffinity: "soft"


