nodeSets:
  - name: hot-nodes
    count: 3
    config:
      node.roles: ["master", "data_hot", "ingest"]
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: managed-premium
          resources:
            requests:
              storage: 50Gi
    podResources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
 
  - name: warm-nodes
    count: 2
    config:
      node.roles: ["data_warm"]
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: managed-standard
          resources:
            requests:
              storage: 100Gi
    podResources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
 
  - name: cold-nodes
    count: 1
    config:
      node.roles: ["data_cold"]
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: managed-standard
          resources:
            requests:
              storage: 200Gi
    podResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"